# Support this project by becoming a sponsor
# Developed and maintained by Lucas Costa
# GitHub Sponsors: https://github.com/sponsors/evaristocosta
# Buy me a coffee: https://www.buymeacoffee.com/lucascosta74

github: evaristocosta
buy_me_a_coffee: lucascosta74
# Your support means a lot! Thank you!
