"""
Constantes e dados relacionados a referências bíblicas
"""

from typing import Dict, List, Tuple

# Mapeamento de nomes de livros bíblicos normalizados para códigos da API
BIBLE_BOOK_MAP: Dict[str, str] = {
    "genesis": "gn",
    "exodo": "ex",
    "levitico": "lv",
    "numeros": "nm",
    "deuteronomio": "dt",
    "josue": "js",
    "juizes": "jz",
    "rute": "rt",
    "1samuel": "1sm",
    "2samuel": "2sm",
    "1reis": "1rs",
    "2reis": "2rs",
    "1cronicas": "1cr",
    "2cronicas": "2cr",
    "esdras": "ed",
    "neemias": "ne",
    "ester": "et",
    "jo": "job",
    "salmos": "sl",
    "proverbios": "pv",
    "eclesiastes": "ec",
    "cantico": "ct",
    "canticos": "ct",
    "cantares": "ct",
    "isaias": "is",
    "jeremias": "jr",
    "lamentacoes": "lm",
    "ezequiel": "ez",
    "daniel": "dn",
    "oseias": "os",
    "joel": "jl",
    "amos": "am",
    "obadias": "ob",
    "jonas": "jn",
    "miqueias": "mq",
    "naum": "na",
    "habacuque": "hc",
    "sofonias": "sf",
    "ageu": "ag",
    "zacarias": "zc",
    "malaquias": "ml",
    "mateus": "mt",
    "marcos": "mc",
    "lucas": "lc",
    "joao": "jo",
    "atos": "at",
    "romanos": "rm",
    "1corintios": "1co",
    "2corintios": "2co",
    "galatas": "gl",
    "efesios": "ef",
    "filipenses": "fp",
    "colossenses": "cl",
    "1tessalonicenses": "1ts",
    "2tessalonicenses": "2ts",
    "1timoteo": "1tm",
    "2timoteo": "2tm",
    "tito": "tt",
    "filemom": "fm",
    "hebreus": "hb",
    "tiago": "tg",
    "1pedro": "1pe",
    "2pedro": "2pe",
    "1joao": "1jo",
    "2joao": "2jo",
    "3joao": "3jo",
    "judas": "jd",
    "apocalipse": "ap",
}

# Lista de nomes de livros bíblicos (sem normalização) para busca
# Ordenados por prioridade: mais longos/específicos primeiro
BIBLE_BOOK_PATTERNS: List[Tuple[str, ...]] = [
    # Livros com números
    ("1 samuel", "1samuel", "1 sm"),
    ("2 samuel", "2samuel", "2 sm"),
    ("1 reis", "1reis", "1 rs"),
    ("2 reis", "2reis", "2 rs"),
    ("1 cronicas", "1cronicas", "1 cr"),
    ("2 cronicas", "2cronicas", "2 cr"),
    ("1 corintios", "1corintios", "1 co"),
    ("2 corintios", "2corintios", "2 co"),
    ("1 tessalonicenses", "1tessalonicenses", "1 ts"),
    ("2 tessalonicenses", "2tessalonicenses", "2 ts"),
    ("1 timoteo", "1timoteo", "1 tm"),
    ("2 timoteo", "2timoteo", "2 tm"),
    ("1 pedro", "1pedro", "1 pe"),
    ("2 pedro", "2pedro", "2 pe"),
    ("1 joao", "1joao", "1 jo"),
    ("2 joao", "2joao", "2 jo"),
    ("3 joao", "3joao", "3 jo"),
    # Livros com nomes compostos
    ("cantico dos canticos", "canticos", "cantico de canticos", "cantares"),
    # Livros simples mais longos primeiro
    ("apocalipse", "ap"),
    ("deuteronomio",),
    ("eclesiastes",),
    ("filipenses",),
    ("colossenses",),
    ("lamentacoes",),
    ("tessalonicenses",),
    ("genesis",),
    ("exodo",),
    ("levitico",),
    ("numeros",),
    ("josue",),
    ("juizes",),
    ("samuel",),
    ("cronicas",),
    ("esdras",),
    ("neemias",),
    ("ester",),
    ("salmos",),
    ("proverbios",),
    ("isaias",),
    ("jeremias",),
    ("ezequiel",),
    ("daniel",),
    ("oseias",),
    ("joel",),
    ("amos",),
    ("obadias",),
    ("jonas",),
    ("miqueias",),
    ("naum",),
    ("habacuque",),
    ("sofonias",),
    ("ageu",),
    ("zacarias",),
    ("malaquias",),
    ("mateus",),
    ("marcos",),
    ("lucas",),
    ("joao",),
    ("atos",),
    ("romanos",),
    ("corintios",),
    ("galatas",),
    ("efesios",),
    ("timoteo",),
    ("tito",),
    ("filemom",),
    ("hebreus",),
    ("tiago",),
    ("pedro",),
    ("judas",),
    ("rute",),
]
